# pull in deidentified tables
targets::tar_make(targets::contains("data_raw"))
targets::tar_load(targets::contains("data_raw"))
# pull in metadata from restricted zenodo deposit
metadata_csv <- readr::read_csv(file = "data/metadata.csv")

metadata_csv$table_name |> unique()

# left_join on field names

# authorship table
auth_metadata <- metadata_csv |> 
  dplyr::filter(table_name =="Authorship") 

auth_df <- data.frame(field_name=names(authorship_data_raw))

auth_df_metadata <- dplyr::left_join(auth_df,auth_metadata)


auth_df_metadata_complete <- auth_df_metadata |>
  dplyr::mutate(
    primary_key = dplyr::case_when(
      is.na(primary_key) ~ FALSE,
      TRUE ~ primary_key
    )
  ) |>
  dplyr::mutate(
    field_desc = dplyr::case_when(
      field_name == "id" ~ "Unique record id generated by Airtable",
      field_name == "created_time" ~ "Date and time when the record was generated",
      TRUE ~ field_desc
    )
  )

readr::write_csv(auth_df_metadata_complete,"data/20671970/authorship_metadata.csv")

# contributors 
contrib_metadata <- metadata_csv |> 
  dplyr::filter(table_name =="Contributors") |>
  dplyr::select(-c(table_name,field_type))

contrib_df <- data.frame(field_name=names(contributor_data_raw))

contrib_df_metadata <- dplyr::left_join(contrib_df,contrib_metadata)

contrib_df_metadata_complete <- contrib_df_metadata |>
  dplyr::mutate(
    primary_key = dplyr::case_when(
      field_name == "id_1" ~ TRUE,
      field_name == "id" ~ FALSE,
      is.na(primary_key) ~ FALSE,
      TRUE ~ primary_key
    )
  ) |>
  dplyr::mutate(
    field_desc = dplyr::case_when(
      field_name == "id_1" ~ "Automatically generated unique id for a contributor.",
      field_name == "id" ~ "Unique record id generated by Airtable",
      field_name == "screenshots_file_paths" ~ "File paths to screenshots of pronoun evidence",
      TRUE ~ field_desc
    )
  )

readr::write_csv(contrib_df_metadata_complete,"data/20671970/contributors_metadata.csv")

# publications

pubs_metadata <- metadata_csv |> 
  dplyr::filter(table_name =="Publications") |>
  dplyr::select(-c(table_name,field_type))

pubs_df <- data.frame(field_name=names(publication_data_raw))

pubs_df_metadata <- dplyr::left_join(pubs_df,pubs_metadata)

pubs_df_metadata_complete <- pubs_df_metadata |>
  dplyr::mutate(
    primary_key = dplyr::case_when(
      is.na(primary_key) ~ FALSE,
      TRUE ~ primary_key
    )
  ) |>
  dplyr::mutate(
    field_desc = dplyr::case_when(
      field_name == "id" ~ "Unique record id generated by Airtable",
      field_name == "created_time" ~ "Date and time when the record was generated",
      field_name == "author_team_size" ~ "Number of authors listed on publication",
      field_name == "source_display_name" ~ "Plain language name of a journal or other publication source e.g. Nature",
      field_name == "source_id" ~ "OpenAlex unique identifier for a journal or publication source",
      TRUE ~ field_desc
      
    )
  )
  

readr::write_csv(pubs_df_metadata_complete,"data/20671970/publications_metadata.csv")
  